// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSjX-lzTx_HlSC9pVR-HIS-06-16kPG30',
    appId: '1:392244606153:android:9d0dcab2d99ce2ed848918',
    messagingSenderId: '392244606153',
    projectId: 'qring-99f90',
    storageBucket: 'qring-99f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYI1Uwbcs-6EIj_L_Gq4YDtmz2c8D9NQ',
    appId: '1:392244606153:ios:c02ead460605b8f2848918',
    messagingSenderId: '392244606153',
    projectId: 'qring-99f90',
    storageBucket: 'qring-99f90.appspot.com',
    iosClientId: '392244606153-etoggeuug9v3u93rf8lv3shq4ag0la48.apps.googleusercontent.com',
    iosBundleId: 'com.example.qringMultiPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyYI1Uwbcs-6EIj_L_Gq4YDtmz2c8D9NQ',
    appId: '1:392244606153:ios:c02ead460605b8f2848918',
    messagingSenderId: '392244606153',
    projectId: 'qring-99f90',
    storageBucket: 'qring-99f90.appspot.com',
    iosClientId: '392244606153-etoggeuug9v3u93rf8lv3shq4ag0la48.apps.googleusercontent.com',
    iosBundleId: 'com.example.qringMultiPlatform',
  );
}
